import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Instagram',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  const condition = false;
  return (
    <html lang="en">
      <body>
        <div className='grid grid-cols-12'>
          <div className='col-span-2'>
            <Navbar />
          </div>
          <div className='col-span-10'>
            {children}
        </div>
        </div>
      </body>
    </html>
  )
}
